apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rgauss-devcon-2018-backend-service.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "rgauss-devcon-2018-backend-service.fullname" . }}
data:
  tika-config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <properties>
        <parsers>
            <parser class="org.apache.tika.parser.recognition.ObjectRecognitionParser">
                <mime>image/jpeg</mime>
                <mime>image/png</mime>
                <mime>image/gif</mime>
                <params>
                    <param name="apiBaseUri" type="uri">http://{{ .Release.Name }}-inception-rest-tika:8764/inception/v4</param>
                    <param name="topN" type="int">2</param>
                    <param name="minConfidence" type="double">0.4</param>
                    <param name="class" type="string">org.apache.tika.parser.recognition.tf.TensorflowRESTRecogniser</param>
                </params>
            </parser>
        </parsers>
    </properties>

