replicaCount: 1
#registryPullSecrets: quay-registry-secret

image:
  repository: alfresco/alfresco-event-gateway-poc
  tag: 0.1-SNAPSHOT
  pullPolicy: IfNotPresent
  internalPort: 8080
service:
  name: alfresco-event-gateway-poc
  # If running on AWS choose LoadBalancer as service Type
  type: NodePort
  externalPort: 8585
ingress:
  path: /alfresco-event-gateway-poc
eventgateway:
  kafka:
  # Kafka host is currently expected at .Release.Name-kafka-poc 
  #  host: kafka
    port: 9092
messaging:
  broker:
    url: amqp://activemq:5672
kafka:
  replicas: 1
  zookeeper:
    servers: 1
  configurationOverrides:
    offsets.topic.replication.factor: 1